name: Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        
    
    steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 7
        run_install: false
          
    - name: Install dependencies
      run: pnpm install
      
    - name: Build
      run: pnpm run build --if-present
      
    - name: Test
      run: pnpm test
